### ISSUE TITLE
Does it work with Turzx 5" ?

### ISSUE THREAD

**Issue by jovantehno** [mathoudebine/turing-smart-screen-python#208] opened 2023-04-28 19:20 UTC
I have tried making config and applying theme, but nothing happens. Is the turzx 5" supported?

**Comment by mathoudebine** [comment] 2023-04-28 20:03
Hello, the 5" version is not currently supported, but development has started: you can check for progress in this issue #90

**Comment by mathoudebine** [comment] 2023-05-02 16:40
Closed as duplicate of #90

**Closed by mathoudebine** 2023-05-02 16:40 UTC
Labels: enhancement
